name: mikdenman_test
favicon: null
layout_spectrum: 0.5639511269982904
typography_spectrum: 0.4160017173271626
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors: []
  brandStrength: 0.06372183188796043
  lightness: 0.9267702831421047
  saturation: 0.7041487316600978
  rhythmicContrast: 0.4336437867023051
purpose: []
