name: mikdenman_test
favicon: null
layout_spectrum: 1
typography_spectrum: 0.48357
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#34beef'
    - '#fddac4'
    - '#cf7076'
    - '#8f465a'
    - '#3d1122'
  brandStrength: 0
  lightness: 0.9267702831421047
  saturation: 0.5
  rhythmicContrast: 0.4336437867023051
purpose: []
